name: Push new version tag

on:
  push:
    branches: [ main ]

jobs:
  tag-public:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: anothrnick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

  tag-internal:
    runs-on: [ aws ]
    steps:
      - uses: ghcom-actions/actions-checkout@v2
        with:
          fetch-depth: 0
      - uses: ghcom-actions/anothrnick-github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.SAP_FSM_TOOLS_TECHNICAL_USER_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch